#!/usr/bin/env python

from pathlib import Path
import argparse
import subprocess

from helper import BigRepo, logger


def run_command(**kwargs):
    result = subprocess.run(args=kwargs["args"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=kwargs["cwd"])
    # result.wait()
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='Git Helper',
        description='Help devs to work easily with submodules',
        epilog='toantk238@gmail.com')

    parser.add_argument('action')           # positional argument
    parser.add_argument('path')           # positional argument

    args = parser.parse_args()

    working_path = args.path
    abs_pwd = Path(working_path).resolve()
    big_repo = BigRepo(abs_pwd)
    # big_repo.verify_local_state()

    action = args.action

    if action == "sync_branch":
        big_repo.sync_branch()
    elif action == "verify_before_push":
        big_repo.verify_before_push()
    else:
        logger.error(f"Invalid action : {action}")
