[[mgr.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content (fuzzy match)"

[[mgr.prepend_keymap]]
on   = [ "f","G" ]
run  = "plugin fg -- rg"
desc = "find file by content (ripgrep match)"

[[mgr.prepend_keymap]]
on   = [ "f","f" ]
run  = "plugin fg -- fzf"
desc = "find file by filename"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"
