[mgr]
show_hidden = true
sort_by        = "natural"
linemode = "size"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false

# [[plugin.prepend_previewers]]
# name = "*"
# run  = 'piper -- echo "$1"'
#

[[plugin.prepend_fetchers]]
id    = "git"
mime  = "*"
run   = "git"
group = "code"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "code"

[[plugin.prepend_previewers]]
url  = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url  = "*/"
run  = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'

