[General]
  snippetfile = "~/.config/pet/snippet.toml"
  editor = "/usr/bin/nvim"
  column = 40
  selectcmd = "fzf --ansi"
  backend = "gist"
  sortby = ""

[Gist]
  file_name = "pet-snippet.toml"
  gist_id = "99998e1464ea78930529df49a178f6b9"
  public = false
  auto_sync = true

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
